name: 'xelatex Action'
description: 'Runs xelatex' 
author: "Voioo"
branding:
  icon: 'file-text'
  color: 'blue'
inputs:
  file:
    description: 'File to be compiled'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
